# Generated by Django 5.0.7 on 2024-07-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
