# Generated by Django 5.0.7 on 2024-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0003_alter_customuser_email_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
