# Generated by Django 5.0.7 on 2024-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
