# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: >-
          ^static/css/dist/styles\.css$|theme/static/css/dist/styles\.css$|\.md$|.pre-commit-config.yaml$
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-import-order
          - flake8-polyfill
          - flake8-quotes
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML, types-toml]
  - repo: local
    hooks:
      - id: build-tailwind
        name: Build Tailwind
        entry: sh -c "python -m services.blog.manage tailwind build" # && python -m services.blog.manage collectstatic --noinput"
        language: system
        pass_filenames: false
        stages: [commit]
