x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/opt/project
  restart: unless-stopped
  env_file:
    - .env

services:
  # blog:
  #   <<: *default-app
  #   command: python -m services.site.manage runserver 0.0.0.0:8000
  #   ports:
  #     - '8001:8000'
  #   depends_on:
  #     - tailwind

  # shop:
  #   <<: *default-app
  #   command: >
  #     sh -c "celery -A services.shop.shop worker -l info &
  #            python -m services.shop.manage runserver 0.0.0.0:8000"
  #   ports:
  #     - '8002:8000'
  #   depends_on:
  #     - stripe
  #     - tailwind
  #     - rabbitmq
  #     - redis

  app:
    <<: *default-app
    command: >
      sh -c "celery -A services.site worker -l info &
             python -m services.manage runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - stripe
      - tailwind
      - rabbitmq
      - redis

  tailwind:
    <<: *default-app
    command: python -m services.manage tailwind start
    tty: true

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis
    ports:
      - '6379:6379'

  stripe:
    image: stripe/stripe-cli
    ports:
      - '12111:12111'
    env_file:
      - .env
    entrypoint:
      [
        'sh',
        '-c',
        'stripe listen --forward-to app:8000/payment/webhook/ --api-key $STRIPE_SECRET_KEY',
      ]
    volumes:
      - ./stripe:/app
