# Generated by Django 5.0.6 on 2024-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
