# Generated by Django 5.0.6 on 2024-07-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_verse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
    ]
