# Generated by Django 5.0.6 on 2024-07-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_options_rename_created_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
