# Generated by Django 5.0.6 on 2024-07-06 10:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('image', models.URLField(max_length=500)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'id',
                    models.CharField(
                        default=uuid.uuid4,  # type: ignore
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True
                    )
                ),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
