# Generated by Django 5.0.6 on 2024-07-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_book_post_chapter_verse_post_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_id',
            new_name='book',
        ),
    ]
